name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          # linux adm
          - os: ubuntu-latest
            platform: linux_amd64
            go-version: 1.23
          - os: ubuntu-latest
            platform: linux_amd64
            go-version: 1.24
          - os: ubuntu-latest
            platform: linux_amd64
            go-version: 1.25
          - os: ubuntu-latest
            platform: linux_amd64
            go-version: stable
          # linux arm
          - os: ubuntu-24.04-arm
            platform: linux_arm64
            go-version: 1.25
          - os: ubuntu-24.04-arm
            platform: linux_arm64
            go-version: stable
          # darwin
          - os: macos-15
            platform: darwin_amd64
            go-version: "stable"
          - os: macos-15
            platform: darwin_arm64
            go-version: "stable"
          # windows
          - os: windows-latest
            platform: windows_amd64
            go-version: "stable"
          - os: windows-latest
            platform: windows_arm64
            go-version: "stable"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -v -race ./...
      - name: Build
        run: go build -v ./...
